"""Students table

Revision ID: 314cd4c3db2f
Revises: 
Create Date: 2023-08-18 16:59:53.848889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314cd4c3db2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('faculty', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
