"""Initial migration

Revision ID: 512491023a2e
Revises: 
Create Date: 2023-10-01 18:30:25.316138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512491023a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fullname', sa.String(
                        length=120), nullable=False),
                    sa.Column('room', sa.String(length=50), nullable=False),
                    sa.Column('faculty', sa.String(
                        length=100), nullable=False),
                    sa.Column('login', sa.String(length=80), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=128), nullable=False),
                    sa.Column('photo', sa.String(length=250), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('qr_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('scanned_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_code')
    op.drop_table('student')
    # ### end Alembic commands ###
