"""third

Revision ID: 784cb89ff3d1
Revises: 8fa2265d7d65
Create Date: 2023-08-20 21:05:01.502961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784cb89ff3d1'
down_revision = '8fa2265d7d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
